# Generated by Django 6.0.7 on 2026-07-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gust_count', models.IntegerField()),
                ('Reservation_time', models.DateField(auto_now=True)),
                ('comments', models.CharField(max_length=10000)),
            ],
        ),
    ]
